import type { Metadata } from "next";
import {IBM_Plex_Sans} from "next/font/google"
import "./globals.css";

const ibm_plex_sans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: "300"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`w-full antialiased ${ibm_plex_sans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
